from django.urls import path

from .views import (
    addon_add_view,
    addon_delete_view,
    addon_update_view,
    addons_apply_view,
    addons_export_excel_view,
    addons_export_pdf_view,
    addons_view,
    categories_apply_view,
    categories_export_excel_view,
    categories_export_pdf_view,
    categories_view,
    coupon_add_view,
    coupon_delete_view,
    coupon_expire_view,
    coupon_update_view,
    customer_add_view,
    customer_delete_view,
    customer_update_view,
    category_add_view,
    category_delete_view,
    category_update_view,
    dashboard_view,
    item_add_view,
    item_delete_view,
    item_update_view,
    invoice_delete_view,
    kitchen_order_action_view,
    items_view,
    login_view,
    logout_view,
    page_view,
    pos_order_cancel_view,
    pos_order_detail_view,
    pos_order_draft_view,
    pos_order_latest_view,
    pos_order_place_view,
    payment_settings_view,
    print_settings_view,
    role_add_view,
    role_permissions_update_view,
    register_view,
    store_settings_view,
    tables_add_view,
    tables_delete_view,
    tables_reorder_view,
    tables_toggle_status_view,
    tables_update_view,
    tax_add_view,
    tax_delete_view,
    tax_update_view,
    users_add_view,
    users_delete_view,
    users_permissions_update_view,
    users_update_view,
    username_check_view,
)


urlpatterns = [
    path("", login_view, name="home"),
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("htmx/username-check/", username_check_view, name="username_check"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("categories/", categories_view, name="categories"),
    path("categories/apply/", categories_apply_view, name="categories_apply"),
    path("categories/export/pdf/", categories_export_pdf_view, name="categories_export_pdf"),
    path("categories/export/excel/", categories_export_excel_view, name="categories_export_excel"),
    path("categories/add/", category_add_view, name="category_add"),
    path("categories/update/", category_update_view, name="category_update"),
    path("categories/delete/", category_delete_view, name="category_delete"),
    path("coupons/add/", coupon_add_view, name="coupon_add"),
    path("coupons/update/", coupon_update_view, name="coupon_update"),
    path("coupons/delete/", coupon_delete_view, name="coupon_delete"),
    path("coupons/expire/", coupon_expire_view, name="coupon_expire"),
    path("addons/", addons_view, name="addons"),
    path("addons/apply/", addons_apply_view, name="addons_apply"),
    path("addons/export/pdf/", addons_export_pdf_view, name="addons_export_pdf"),
    path("addons/export/excel/", addons_export_excel_view, name="addons_export_excel"),
    path("addons/add/", addon_add_view, name="addon_add"),
    path("addons/update/", addon_update_view, name="addon_update"),
    path("addons/delete/", addon_delete_view, name="addon_delete"),
    path("items/", items_view, name="items"),
    path("items/add/", item_add_view, name="item_add"),
    path("items/update/", item_update_view, name="item_update"),
    path("items/delete/", item_delete_view, name="item_delete"),
    path("customers/add/", customer_add_view, name="customer_add"),
    path("customers/update/", customer_update_view, name="customer_update"),
    path("customers/delete/", customer_delete_view, name="customer_delete"),
    path("invoices/delete/", invoice_delete_view, name="invoice_delete"),
    path("tables/add/", tables_add_view, name="tables_add"),
    path("tables/update/", tables_update_view, name="tables_update"),
    path("tables/delete/", tables_delete_view, name="tables_delete"),
    path("tables/reorder/", tables_reorder_view, name="tables_reorder"),
    path("tables/toggle-status/", tables_toggle_status_view, name="tables_toggle_status"),
    path("tax/add/", tax_add_view, name="tax_add"),
    path("tax/update/", tax_update_view, name="tax_update"),
    path("tax/delete/", tax_delete_view, name="tax_delete"),
    path("users/add/", users_add_view, name="users_add"),
    path("users/update/", users_update_view, name="users_update"),
    path("users/delete/", users_delete_view, name="users_delete"),
    path("users/permissions/update/", users_permissions_update_view, name="users_permissions_update"),
    path("roles/add/", role_add_view, name="role_add"),
    path("roles/permissions/update/", role_permissions_update_view, name="role_permissions_update"),
    path("pos/orders/place/", pos_order_place_view, name="pos_order_place"),
    path("pos/orders/draft/", pos_order_draft_view, name="pos_order_draft"),
    path("pos/orders/cancel/", pos_order_cancel_view, name="pos_order_cancel"),
    path("pos/orders/latest/", pos_order_latest_view, name="pos_order_latest"),
    path("pos/orders/<int:order_id>/", pos_order_detail_view, name="pos_order_detail"),
    path("kitchen/orders/<int:order_id>/<slug:action>/", kitchen_order_action_view, name="kitchen_order_action"),
    path("payment-settings/", payment_settings_view, name="payment_settings"),
    path("print-settings/", print_settings_view, name="print_settings"),
    path("store-settings/", store_settings_view, name="store_settings"),
    path("logout/", logout_view, name="logout"),
    path("<slug:page>/", page_view, name="page"),
]
