# Generated by Django 6.0.3 on 2026-03-04 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='categories/')),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ['-created_on', 'name'],
            },
        ),
    ]
