# Generated by Django 6.0.3 on 2026-03-05 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("image", models.FileField(blank=True, null=True, upload_to="addons/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("Active", "Active"), ("Expired", "Expired")], default="Active", max_length=20)),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addons", to="pos_app.category")),
            ],
            options={
                "ordering": ["-created_on", "name"],
                "unique_together": {("item", "name")},
            },
        ),
    ]
