# Generated by Django 6.0.3 on 2026-03-05 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0003_addon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="items/")),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="menu_items", to="pos_app.category")),
                ("tax", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="pos_app.tax")),
            ],
            options={
                "ordering": ["-created_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemAddon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="item_addons", to="pos_app.item")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ItemVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size", models.CharField(max_length=80)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variations", to="pos_app.item")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
