# Generated by Django 6.0.3 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0004_item_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tax",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="tax",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("Inclusive / Exclusive", "Inclusive / Exclusive"),
                    ("Exclusive", "Exclusive"),
                ],
                default="Exclusive",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="tax",
            options={"ordering": ["title"]},
        ),
    ]
