# Generated by Django 6.0.3 on 2026-03-05 00:00

import decimal
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0005_tax_title_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="addon",
            constraint=models.CheckConstraint(condition=models.Q(price__gt=0), name="addon_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AlterField(
            model_name="item",
            name="net_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(condition=models.Q(price__gt=0), name="item_price_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(condition=models.Q(net_price__gt=0), name="item_net_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="itemvariation",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="itemvariation",
            constraint=models.CheckConstraint(condition=models.Q(price__gt=0), name="item_variation_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="itemaddon",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AlterUniqueTogether(
            name="itemaddon",
            unique_together={("item", "name")},
        ),
        migrations.AddConstraint(
            model_name="itemaddon",
            constraint=models.CheckConstraint(condition=models.Q(price__gt=0), name="item_addon_price_gt_zero"),
        ),
    ]
