# Generated by Django 6.0.3 on 2026-03-05 00:00

import decimal
from django.core.validators import MinValueValidator
import django
from django.db import migrations, models


def compat_check_constraint(q_obj, name):
    if django.VERSION >= (5, 1):
        return models.CheckConstraint(condition=q_obj, name=name)
    return models.CheckConstraint(check=q_obj, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0005_tax_title_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="addon",
            constraint=compat_check_constraint(models.Q(price__gt=0), "addon_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AlterField(
            model_name="item",
            name="net_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=compat_check_constraint(models.Q(price__gt=0), "item_price_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=compat_check_constraint(models.Q(net_price__gt=0), "item_net_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="itemvariation",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AddConstraint(
            model_name="itemvariation",
            constraint=compat_check_constraint(models.Q(price__gt=0), "item_variation_price_gt_zero"),
        ),
        migrations.AlterField(
            model_name="itemaddon",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))]),
        ),
        migrations.AlterUniqueTogether(
            name="itemaddon",
            unique_together={("item", "name")},
        ),
        migrations.AddConstraint(
            model_name="itemaddon",
            constraint=compat_check_constraint(models.Q(price__gt=0), "item_addon_price_gt_zero"),
        ),
    ]
