# Generated by Django 6.0.3 on 2026-03-05 09:00

import decimal
import django.db.models.deletion
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0006_positive_price_and_itemaddon_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_no", models.CharField(blank=True, max_length=30, unique=True)),
                ("token_no", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("Draft", "Draft"), ("Placed", "Placed"), ("Cancelled", "Cancelled"), ("Voided", "Voided")], default="Placed", max_length=20)),
                ("order_type", models.CharField(choices=[("Dine In", "Dine In"), ("Takeaway", "Takeaway"), ("Delivery", "Delivery")], default="Dine In", max_length=20)),
                ("customer_name", models.CharField(default="Walk-in Customer", max_length=120)),
                ("table_name", models.CharField(blank=True, max_length=60)),
                ("note", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=decimal.Decimal("18.00"), max_digits=5)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("service_charge", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="pos_app.user")),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=150)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(decimal.Decimal("0.01"))])),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(decimal.Decimal("0.01"))])),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="pos_app.order")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
