# Generated by Django 6.0.1 on 2026-03-05 10:28

from django.db import migrations, models


def backfill_customer_ids(apps, schema_editor):
    Customer = apps.get_model("pos_app", "Customer")
    for customer in Customer.objects.all().order_by("id"):
        if not customer.customer_id:
            customer.customer_id = f"CR{customer.id:04d}"
            customer.save(update_fields=["customer_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.RunPython(backfill_customer_ids, migrations.RunPython.noop),
    ]
