# Generated by Django 6.0.1 on 2026-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0017_diningtable_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('New', 'New'), ('In Kitchen', 'In Kitchen'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
