# Generated by Django 6.0.1 on 2026-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0018_alter_diningtable_options_order_kitchen_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_bank",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_card",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_card_reader",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_cash",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_paypal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_qr_reader",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesetting",
            name="enable_payment_wallet",
            field=models.BooleanField(default=True),
        ),
    ]
