# Generated by Django 6.0.1 on 2026-03-08 12:20

import django
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def compat_check_constraint(q_obj, name):
    if django.VERSION >= (5, 1):
        return models.CheckConstraint(condition=q_obj, name=name)
    return models.CheckConstraint(check=q_obj, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0019_storesetting_payment_toggles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coupon_code", models.CharField(max_length=50, unique=True)),
                ("discount_type", models.CharField(choices=[("Percentage", "Percentage"), ("Fixed Amount", "Fixed Amount")], max_length=20)),
                ("discount_amount", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("start_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="coupons", to="pos_app.category")),
            ],
            options={
                "ordering": ["-created_on", "coupon_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=compat_check_constraint(models.Q(("discount_amount__gt", 0)), "coupon_discount_amount_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=compat_check_constraint(models.Q(("expiry_date__gte", models.F("start_date"))), "coupon_expiry_on_or_after_start"),
        ),
    ]
