# Generated by Django 6.0.1 on 2026-03-08 12:52

import django
import django.db.models.deletion
from django.db import migrations, models


def compat_check_constraint(q_obj, name):
    if django.VERSION >= (5, 1):
        return models.CheckConstraint(condition=q_obj, name=name)
    return models.CheckConstraint(check=q_obj, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0020_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="applies_to_all_categories",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="coupons", to="pos_app.category"),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=compat_check_constraint(
                models.Q(applies_to_all_categories=True) | models.Q(valid_category__isnull=False),
                "coupon_has_scope",
            ),
        ),
    ]
