# Generated by Django 6.0.1 on 2026-03-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0021_coupon_all_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="applies_to_all_items",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="coupons", to="pos_app.item"),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(applies_to_all_items=True) | models.Q(valid_item__isnull=False),
                name="coupon_has_item_scope",
            ),
        ),
    ]
